"use client";

import { useRef, useState } from "react";

type Position = { latitude: number; longitude: number; accuracyMeters: number; occurredAt: string };

function describeError(error: GeolocationPositionError) {
  if (error.code === error.PERMISSION_DENIED) return "Location permission was denied. Enable it for this browser/app, then try again.";
  if (error.code === error.TIMEOUT) return "No location fix arrived within 30 seconds. Try again near a window or use a manual private capture instead.";
  return `Location could not be read: ${error.message || "unknown browser error"}.`;
}

export function FieldTrace() {
  const [consent, setConsent] = useState(false); const [note, setNote] = useState(""); const [position, setPosition] = useState<Position>(); const [message, setMessage] = useState("A Field Trace stays only in this tab until you explicitly save it into the encrypted Vault."); const [busy, setBusy] = useState(false); const requested = useRef(false);
  function requestLocation() { if (!consent || requested.current || !("geolocation" in navigator)) return; requested.current = true; setBusy(true); setMessage("Looking for a coarse location fix. It is not being saved."); navigator.geolocation.getCurrentPosition((result) => { setPosition({ latitude: result.coords.latitude, longitude: result.coords.longitude, accuracyMeters: result.coords.accuracy, occurredAt: new Date(result.timestamp).toISOString() }); setMessage(`Location fix available at ±${Math.round(result.coords.accuracy)} m. Review it before saving.`); setBusy(false); }, (error) => { requested.current = false; setMessage(describeError(error)); setBusy(false); }, { enableHighAccuracy: false, maximumAge: 60_000, timeout: 30_000 }); }
  async function save() { if (!position) return; setBusy(true); try { const response = await fetch("/api/vault", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "record-field-trace", fieldTrace: { ...position, note, consent: true } }) }); const result = await response.json() as { error?: string; captured?: { id: string } }; if (!response.ok || result.error) throw new Error(result.error ?? "The Field Trace could not be saved."); setMessage("Saved as restricted, private, non-canonical Field Trace evidence. It will never appear in public output unless you deliberately promote it."); setPosition(undefined); setNote(""); } catch (error) { setMessage(error instanceof Error ? error.message : "The Field Trace could not be saved."); } finally { setBusy(false); } }
  return <main className="research-main private-review-main"><section className="experiment-hero"><p className="eyebrow"><span /> Storywalker Field Trace</p><h1>Be somewhere first. Decide later whether it belongs in the record.</h1><p>This is separate from Echo Lab. It asks for one coarse live location fix, retains it only in this tab, then requires a second explicit action before encrypting it as restricted private evidence.</p></section><p className="live-notice" role="status">{message}</p><section className="notebook-card vault-card"><p className="section-kicker">One position, not a background trail</p><label className="consent-row"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /> I understand that requesting location reads my current approximate position in this tab; it will not be saved until I choose Save.</label><button type="button" className="primary-button" disabled={!consent || busy || Boolean(position)} onClick={requestLocation}>Request one location fix</button>{position ? <div className="vault-form"><p className="small-note">A private location fix is ready: ±{Math.round(position.accuracyMeters)} m accuracy at {new Date(position.occurredAt).toLocaleString()}. Precise coordinates are intentionally not rendered here.</p><label>Private note (optional)<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={800} placeholder="What happened here? Keep it factual; meaning can come later." /></label><button type="button" className="primary-button" disabled={busy} onClick={save}>Save restricted Field Trace</button><p className="small-note">Uses the active browser-wide Vault session. Unlock once at <a href="/vault">Vault</a>; it expires exactly 15 minutes after unlock.</p></div> : null}</section></main>;
}
