"use client";

import { useMemo, useState } from "react";
import type { RecoveryDecisionAction, StagedRecovery } from "@/lib/private-recovery";
import { buildNextQuestionCohort, questionSignalLabel, type LocalQuestion } from "@/lib/question-cohort";

const actionLabels: Record<Exclude<RecoveryDecisionAction, "revise">, string> = { "accept-evidence": "Accept source evidence", "save-correction-and-accept-evidence": "Save correction and accept evidence", "refuse-interpretation": "Refuse interpretation", "exclude-entirely": "Exclude entirely", "keep-unresolved": "Keep unresolved" };
type ApiResult = { document: StagedRecovery; created: boolean; payloadHash: string } | { error: string };

function sourceLabel(moment: StagedRecovery["moments"][number]) { return `${moment.when.precision} · ${moment.when.start ?? "date unknown"}${moment.where.privateLabel ? ` · ${moment.where.privateLabel}` : " · location unknown"}`; }

function QuestionContext({ question, onProposeThread, busyMomentId }: { question: LocalQuestion; onProposeThread: (momentId: string) => void; busyMomentId?: string }) {
  return <details className="question-context" open>
    <summary>Memory packet · context, not an answer</summary>
    <p className="small-note">These are private source fragments selected locally to make this prompt legible later. They do not resolve it or add a claim.</p>
    {question.context.length ? question.context.map((packet) => <article key={packet.momentId}>
      <h3><a href={`#${packet.momentId}`}>{packet.title}</a></h3>
      <dl>
        <div><dt>Journey</dt><dd>{packet.journey}</dd></div>
        <div><dt>When</dt><dd>{packet.when}</dd></div>
        <div><dt>Where</dt><dd>{packet.where}</dd></div>
        <div><dt>Who</dt><dd>{packet.who.length ? packet.who.join(" · ") : "No person or act is named in this Moment."}</dd></div>
        <div><dt>What</dt><dd>{packet.what.join(" · ")}</dd></div>
        <div><dt>Music</dt><dd>{packet.music.length ? packet.music.join(" · ") : "No music reference recorded in this Moment."}</dd></div>
        <div><dt>How known</dt><dd>{packet.howKnown.join(" · ")}</dd></div>
      </dl>
      {packet.music.length >= 5 ? <button type="button" className="outline-button thread-spark-button" onClick={() => onProposeThread(packet.momentId)} disabled={busyMomentId === packet.momentId}>{busyMomentId === packet.momentId ? "Holding the thread privately…" : "Hold as a private editorial thread"}</button> : null}
    </article>) : <p className="small-note">No direct Moment link has been recorded for this source question yet. Your response will remain private source context rather than being attached to a Moment automatically.</p>}
  </details>;
}

function QuestionConflict({ question }: { question: LocalQuestion }) {
  if (!question.contradictions?.length) return null;
  return <section className="question-conflict">
    <p className="section-kicker">What conflicts</p>
    <ol>{question.contradictions.map((note, index) => <li key={`${index}-${note}`}>{note}</li>)}</ol>
    <p className="small-note">Useful answers include: “the first note is right,” “neither is right — [your correction],” or “leave this unknown for now.”</p>
  </section>;
}

export function PrivateAuthorReview() {
  const [document, setDocument] = useState<StagedRecovery>(); const [message, setMessage] = useState("This screen does not load private material until you explicitly request it."); const [notes, setNotes] = useState<Record<string, string>>({}); const [questionNotes, setQuestionNotes] = useState<Record<string, string>>({}); const [busyMoment, setBusyMoment] = useState<string>(); const [busyQuestion, setBusyQuestion] = useState<string>(); const [busyThread, setBusyThread] = useState<string>(); const [busyInbox, setBusyInbox] = useState(false);
  const journeys = useMemo(() => document?.journeys.map((journey) => ({ ...journey, moments: document.moments.filter((moment) => (document.relationshipOverrides[moment.id]?.primaryJourney ?? moment.journeyCandidate) === journey.id).sort((a, b) => `${a.when.start ?? "9999"}:${a.id}`.localeCompare(`${b.when.start ?? "9999"}:${b.id}`)) })).filter((journey) => journey.moments.length) ?? [], [document]);
  const nextCohort = useMemo(() => document ? buildNextQuestionCohort(document) : [], [document]);
  async function load() { const response = await fetch("/api/private-review", { cache: "no-store" }); const result = await response.json() as StagedRecovery | { error: string }; if (!response.ok || "error" in result) { setMessage("The local private review source could not be loaded."); return; } setDocument(result); setMessage("Private Author-review material loaded locally."); }
  async function decide(momentId: string, action: Exclude<RecoveryDecisionAction, "revise">) { setBusyMoment(momentId); setMessage(action === "save-correction-and-accept-evidence" ? "Saving correction…" : "Saving decision…"); try { const response = await fetch("/api/private-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ momentId, action, note: notes[momentId] ?? document?.review[momentId]?.currentAuthorCorrection?.text }) }); const result = await response.json() as ApiResult; if (!response.ok || "error" in result) { setMessage("No change was made. A correction needs Author wording."); return; } setDocument(result.document); setMessage(result.created ? action === "save-correction-and-accept-evidence" ? "Correction saved and factual evidence accepted." : "Decision saved." : "Already saved — no duplicate audit event was added."); } finally { setBusyMoment(undefined); } }
  async function answerQuestion(question: LocalQuestion) { const response = questionNotes[question.id]?.trim(); if (!response) return; setBusyQuestion(question.id); setMessage("NOVA is preserving and processing your raw answer locally…"); try { const request = await fetch("/api/private-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "answer-question", questionId: question.id, question: question.question, sourceQuestionId: question.sourceQuestionId, response, targetMomentIds: question.evidenceMomentIds }) }); const result = await request.json() as ApiResult & { response?: { claims?: unknown[] } }; if (!request.ok || "error" in result) { setMessage("NOVA did not store the response. Your text remains in the field."); return; } setDocument(result.document); setQuestionNotes((current) => ({ ...current, [question.id]: "" })); setMessage(result.created ? `NOVA saved and locally triaged your ${result.response?.claims?.length ?? 0} author-stated claim(s).` : "That exact response is already in the private NOVA inbox; no duplicate was added."); } finally { setBusyQuestion(undefined); } }
  async function processInbox() { setBusyInbox(true); setMessage("NOVA is processing saved inbox responses locally…"); try { const request = await fetch("/api/private-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "process-inbox" }) }); const result = await request.json() as { document: StagedRecovery; created: number; processed: number; pending: number } | { error: string }; if (!request.ok || "error" in result) { setMessage("NOVA could not process the inbox. No source evidence changed."); return; } setDocument(result.document); setMessage(`NOVA processed ${result.processed} saved response(s); ${result.pending} remain unclassified.`); } finally { setBusyInbox(false); } }
  async function proposeThread(momentId: string) { setBusyThread(momentId); setMessage("NOVA is holding a private editorial thread beside this source cluster…"); try { const request = await fetch("/api/private-review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "propose-thread", momentId, title: "Untitled private editorial thread" }) }); const result = await request.json() as ApiResult; if (!request.ok || "error" in result) { setMessage("NOVA could not create that thread candidate. No evidence was changed."); return; } setDocument(result.document); setMessage(result.created ? "Private thread candidate created. It is editorial, pending, and non-canonical." : "That private thread candidate is already linked to this source cluster."); } finally { setBusyThread(undefined); } }
  return <main className="research-main private-review-main"><section className="experiment-hero"><p className="eyebrow"><span /> Local-only Author review</p><h1>Review evidence, corrections, and interpretation separately.</h1><p>Private evidence is loaded only on request. Corrections keep their source history and do not accept editorial proposals.</p><button type="button" className="primary-button" onClick={load}>Load local private review</button></section><p className="live-notice" role="status">{message}</p>{document ? <>
    <section className="notebook-card"><p className="section-kicker">Private staging summary</p><h2>{document.moments.length} candidates · {document.journeys.length} provisional Journeys · no Episodes</h2><p className="small-note">Every candidate remains private and non-canonical. Factual-evidence and editorial-proposal decisions are independent.</p>{document.threads.filter((thread) => thread.sourceMomentIds.length).length ? <details className="thread-shelf" open><summary>Private editorial thread candidates · {document.threads.filter((thread) => thread.sourceMomentIds.length).length}</summary>{document.threads.filter((thread) => thread.sourceMomentIds.length).map((thread) => <article key={`${thread.title}-${thread.sourceMomentIds.join("-")}`}><b>{thread.title}</b><p>{thread.proposal}</p><small>Anchored to {thread.sourceMomentIds.map((momentId) => <a key={momentId} href={`#${momentId}`}>{momentId}</a>)} · pending · non-canonical</small></article>)}</details> : null}</section>
    <section className="notebook-card cohort-card"><p className="section-kicker">Cohort 2 · NOVA local intake</p><h2>{nextCohort.length} next review prompts</h2><p className="small-note">NOVA preserves your raw answer privately, separates only the lines you explicitly wrote into author-stated claims, and links the evidence shown below. No external model call occurs.</p>{nextCohort.length ? <ol className="question-cohort">{nextCohort.map((question) => { const busy = busyQuestion === question.id; return <li key={question.id}><p><span className="knowledge-tag proposed">{questionSignalLabel(question.signal)}</span> {question.question}</p><small>{question.whyNow}</small>{question.evidenceMomentIds.length ? <span className="question-evidence">Evidence: {question.evidenceMomentIds.map((momentId) => <a key={momentId} href={`#${momentId}`}>{momentId}</a>)}</span> : <span className="question-evidence">Source: {question.sourceQuestionId}</span>}<QuestionConflict question={question} /><QuestionContext question={question} onProposeThread={proposeThread} busyMomentId={busyThread} /><label className="nova-answer">Answer in your own words<textarea value={questionNotes[question.id] ?? ""} onChange={(event) => setQuestionNotes((current) => ({ ...current, [question.id]: event.target.value }))} disabled={busy} placeholder="Raw notes are kept privately; NOVA will not add meaning you did not state." /></label><button type="button" className="outline-button" onClick={() => answerQuestion(question)} disabled={busy || !(questionNotes[question.id] ?? "").trim()}>{busy ? "Saving privately…" : "Send to NOVA intake"}</button></li>; })}</ol> : <p className="small-note">No unanswered source question or structural evidence gap is currently eligible for this cohort.</p>}{document.questionResponses.length ? <details className="nova-inbox"><summary>NOVA inbox · {document.questionResponses.length} saved response{document.questionResponses.length === 1 ? "" : "s"}</summary><p className="small-note">Answers are processed immediately when sent. Older saved answers can be processed once here; this only creates private, non-canonical author evidence or marks an intentional unknown/import dependency.</p><button type="button" className="outline-button" onClick={processInbox} disabled={busyInbox}>{busyInbox ? "Processing inbox…" : "Process saved inbox"}</button>{[...document.questionResponses].reverse().map((response) => <article key={response.id}><b>{response.question}</b><p>{response.response}</p><small>{response.claims.length} author-stated claim{response.claims.length === 1 ? "" : "s"} · {response.targetMomentIds.length ? response.targetMomentIds.join(" · ") : "no Moment linked"} · {response.triage ? response.triage.status.replaceAll("-", " ") : "awaiting local triage"}</small></article>)}</details> : null}<p className="small-note">Processed evidence remains private and non-canonical. Interpretations and canon remain separate decisions.</p></section>
    {journeys.map((journey) => <section className="private-review-grid" key={journey.id}><article className="notebook-card"><p className="section-kicker">Provisional Journey · {journey.moments.length} visible Moments</p><h2>{journey.id}</h2><p className="small-note">Source order remains in the ledger; this view is ordered for review.</p></article><article className="notebook-card"><p className="section-kicker">Evidence review</p>{journey.moments.map((moment) => { const review = document.review[moment.id]; const correction = review.currentAuthorCorrection; const updates = document.postImportEvidence.filter((item) => item.targetMomentIds.includes(moment.id)); const relationship = document.relationshipOverrides[moment.id]; const busy = busyMoment === moment.id; return <details className="private-proposal" id={moment.id} key={moment.id}><summary>{moment.title} <span className="knowledge-tag proposed">{moment.sensitivity}</span></summary><p className="small-note"><span className="knowledge-tag proposed">Factual evidence: {review.factualEvidenceStatus}</span> <span className="knowledge-tag proposed">Editorial proposal: {review.editorialProposalStatus}</span></p>{review.delegatedSourceReview ? <p className="small-note"><span className="knowledge-tag recorded">Delegated source review</span> {review.delegatedSourceReview.acceptedPaths.length} source-backed item{review.delegatedSourceReview.acceptedPaths.length === 1 ? "" : "s"} accepted; unresolved material remains pending.</p> : null}{relationship ? <p className="small-note">Primary Journey: {relationship.primaryJourney} · Cross-Journey: {relationship.crossJourneyCandidates.join(" · ")} · Thread proposal: {relationship.threadProposals.join(" · ")}</p> : null}
      <section className="private-current-version"><p className="section-kicker">Current Author-corrected version</p>{correction ? <><p><b>{correction.effective?.dateLabel ?? "Author correction saved"}</b> · {correction.effective?.precision ?? "Author wording"}</p>{correction.effective?.factualSummary.map((line) => <p key={line}>{line}</p>)}{correction.effective?.unknowns.length ? <p className="small-note">Still unknown: {correction.effective.unknowns.join(" · ")}</p> : null}{correction.effective?.retainedDetails.length ? <p className="small-note">Retained: {correction.effective.retainedDetails.join(" · ")}</p> : null}<p className="small-note">Correction saved · factual evidence accepted · version {correction.version}</p><details><summary>Persisted correction text</summary><p>{correction.text}</p></details></> : <p className="small-note">No Author correction saved. Current state follows the source evidence below.</p>}</section>
      <details><summary>Original source evidence and provenance</summary><p className="small-note">{sourceLabel(moment)} · {moment.reviewStatus} · {moment.canonical ? "canonical" : "non-canonical"}</p><p>{moment.authorStatement || "No Author statement recorded."}</p><h3>Claim ledger</h3>{moment.claimLedger.map((claim, index) => <p key={`${claim.claim}-${index}`}><span className={`knowledge-tag ${claim.evidenceStatus}`}>{claim.evidenceStatus}</span> {claim.claim}</p>)}<h3>Provenance</h3>{moment.provenance.map((item, index) => <p key={`${item.chatTitle}-${index}`}><span className={`knowledge-tag ${item.evidenceStatus}`}>{item.evidenceStatus}</span> {item.chatTitle} · {item.messageDate}</p>)}{moment.unknowns.length ? <p className="small-note">Original unknowns: {moment.unknowns.join(" · ")}</p> : null}</details>
      {updates.length ? <details><summary>Post-import Author evidence ({updates.length})</summary>{updates.flatMap((item) => item.claims).map((claim, index) => <p key={`${claim.claim}-${index}`}><span className={`knowledge-tag ${claim.evidenceStatus}`}>{claim.evidenceStatus}</span> {claim.claim}</p>)}</details> : null}{moment.editorialProposals[0] ? <p><span className="knowledge-tag proposed">Optional editorial proposal</span> {moment.editorialProposals[0]}</p> : null}
      <label>Correction in your own words<textarea value={notes[moment.id] ?? correction?.text ?? ""} onChange={(event) => setNotes((current) => ({ ...current, [moment.id]: event.target.value }))} disabled={busy} /></label><div className="experiment-actions"><button type="button" onClick={() => decide(moment.id, "save-correction-and-accept-evidence")} disabled={busy}>{busy ? "Saving…" : actionLabels["save-correction-and-accept-evidence"]}</button><button type="button" onClick={() => decide(moment.id, "accept-evidence")} disabled={busy}>{actionLabels["accept-evidence"]}</button><button type="button" onClick={() => decide(moment.id, "refuse-interpretation")} disabled={busy}>{actionLabels["refuse-interpretation"]}</button><button type="button" onClick={() => decide(moment.id, "exclude-entirely")} disabled={busy}>{actionLabels["exclude-entirely"]}</button><button type="button" onClick={() => decide(moment.id, "keep-unresolved")} disabled={busy}>{actionLabels["keep-unresolved"]}</button></div><p className="small-note">{review.excluded ? "Excluded from future private editorial use; retained in this private audit." : "No source evidence is deleted by refusal or exclusion."}</p><details><summary>Audit history ({review.decisions.length} decision{review.decisions.length === 1 ? "" : "s"}; {review.auditNotes.length} maintenance note{review.auditNotes.length === 1 ? "" : "s"})</summary>{review.decisions.map((entry, index) => <p key={`${entry.at}-${index}`}>{entry.action} · {entry.at}{entry.note ? ` · ${entry.note}` : ""}</p>)}{review.auditNotes.map((entry, index) => <p key={`${entry.at}-${index}`}>{entry.detail}</p>)}</details></details>; })}</article></section>)}
    <section className="notebook-card"><p className="section-kicker">Original gaps and Author questions</p><h2>{document.unansweredQuestions.length} source questions</h2><ol>{document.unansweredQuestions.map((question) => <li key={question.id}>{question.question} <span className="knowledge-tag proposed">{document.gapState.find((state) => state.questionId === question.id)?.status ?? "unresolved"}</span></li>)}</ol></section>
  </> : null}</main>;
}
