'use client';
import {vaultFetch} from '@/lib/vault-access';
import {VaultUnlockButton} from './vault-access';
import {useState} from 'react';
import type {ResearchSession} from '@/lib/research-session';
export function ResearchNotebook({study,entries,mode='fictional',sourceContext=''}:Pick<ResearchSession,'study'|'entries'> & {mode?:ResearchSession['mode'];sourceContext?:string}){
 const [note,setNote]=useState(''),[windowId,setWindowId]=useState(''),[windows,setWindows]=useState<{id:string;label:string;start:string}[]>([]),[records,setRecords]=useState<{id:string;capturedAt:string;payload:ResearchSession}[]>([]),[status,setStatus]=useState('Session only · not yet saved to the Vault.'),[busy,setBusy]=useState(false),[savedSignature,setSavedSignature]=useState('');
 const signature=JSON.stringify({entries,note,windowId,mode,sourceContext});
 async function request(save=false){setBusy(true);try{const response=await vaultFetch('/api/vault',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(save?{action:'save-research-session',researchSession:{study,title:`${study} · research session`,note,entries,mode,sourceContext,...(windowId?{sourceWindowId:windowId}:{})}}:{action:'list-research-sessions'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Vault request failed');if(save){setSavedSignature(signature);setStatus(`Saved encrypted at ${new Date(data.savedAt).toLocaleTimeString()}. ${windowId?'Author association saved. Reload your XR draft, then enrich its source windows to include this research record.':'Available through Vault search. No journey or XR association was inferred.'}`);}else{setRecords(data.records.filter((r:{payload:ResearchSession})=>r.payload.study===study));setWindows(data.windows);setStatus('Saved sessions loaded. Current unsaved responses are unchanged.');}}catch(e){setStatus(e instanceof Error?e.message:'Could not save. Your current responses remain here.');}finally{setBusy(false);}}
 return <section className="private-audio-card notebook-card"><p className="section-kicker">Research record · from decision to archive</p><h2>Keep the consequence, and the reason.</h2><p>Your choices first change this study. Save a snapshot to keep the responses and refusals encrypted in the Vault. A scene association is an explicit composition decision; it never confirms an event, location or autobiographical meaning.</p><label>Author reflection<textarea value={note} maxLength={4000} onChange={e=>setNote(e.target.value)} placeholder="What changed? What should this proposal never claim?"/></label><div className="experiment-actions"><button disabled={busy} onClick={()=>void request()}>Load saved sessions & scene windows</button><VaultUnlockButton /></div><label>Optional source-window association<select value={windowId} onChange={e=>setWindowId(e.target.value)}><option value="">Keep as a research record only</option>{windows.map(w=><option key={w.id} value={w.id}>{w.start.slice(0,10)} · {w.label} · {w.id}</option>)}</select></label><button className="outline-button" disabled={busy||(!entries.length&&!note.trim())} onClick={()=>void request(true)}>{busy?'Working…':'Save research snapshot to Vault'}</button><p role="status">{status}{savedSignature&&savedSignature!==signature?" Changes since that snapshot are not saved yet.":""}</p><p className="small-note">No automatic save, public export or canonical promotion. Audio files and live coordinates are excluded. Every save creates a separate snapshot.</p><details><summary>Current response history · {entries.length} actions</summary><ol>{entries.map((e,i)=><li key={i}><b>{e.action}</b> · {e.subject}{e.wording?` — ${e.wording}`:''}{e.at?` · ${e.at}`:''}</li>)}</ol></details>{records.length>0&&<details><summary>Saved snapshots · {records.length}</summary>{records.map(r=><article key={r.id}><h3>{r.capturedAt}</h3><p>{r.payload.note||'No reflection added.'}</p><ul>{r.payload.entries.map((e,i)=><li key={i}>{e.action} · {e.subject}{e.wording?` — ${e.wording}`:''}</li>)}</ul><small>{r.id}</small></article>)}</details>}</section>;
}
