'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {episodeSpaces,moveEpisodeSpace,acceptedDensity,type Regime} from '@/lib/journey-experience';
import {geographicToRoom,clipPolygon,type BasemapData} from '@/lib/journey-basemap';
import {atlasProject,atlasDrag,chronologicalHeight,type AtlasView} from '@/lib/atlas-spatial';
import type {XRScene,Decision} from '@/lib/xr-scene';
import css from './xr-geographic-atlas.module.css';
import {XRMemorySound} from './xr-memory-sound';
import {DEFAULT_ATLAS_VIEW,MEMORY_ATLAS_VIEW} from '@/lib/atlas-spatial';
export function XRGeographicAtlas({scene,decisions,activated,onChange,onRegime,onInspect}:{scene:XRScene;decisions:Record<string,Decision>;activated:boolean;onChange:(scene:XRScene)=>void;onRegime:(r:Regime)=>void;onInspect:(i:number)=>void}){
 const spaces=useMemo(()=>episodeSpaces(scene),[scene]),memory=scene.experience?.regime==='MEMORY';
 const [data,setData]=useState<BasemapData|null>(null),[error,setError]=useState(''),[selected,setSelected]=useState(0),[view,setView]=useState<AtlasView>(memory?MEMORY_ATLAS_VIEW:DEFAULT_ATLAS_VIEW),[moving,setMoving]=useState(false),[full,setFull]=useState(false),[inspect,setInspect]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null),hits=useRef<{index:number;x:number;y:number}[]>([]),gesture=useRef<{x:number;y:number;view:AtlasView}|null>(null);
 const current=spaces[Math.min(selected,spaces.length-1)];
 const map=useMemo(()=>{if(!data||!scene.journeyLayout)return [];const projection=scene.journeyLayout.projection;return data.countries.map(country=>({name:country.name,label:geographicToRoom(country.label[0],country.label[1],projection),rings:country.polygons.flatMap(polygon=>polygon.map(ring=>{let points=ring.map(p=>geographicToRoom(p[0],p[1],projection));if(points.some((p,i)=>Math.abs(p.x-points[(i+1)%points.length].x)*projection.metresPerUnit>20000000))return [];for(const distance of [(p:{x:number;z:number})=>p.x+34,(p:{x:number;z:number})=>34-p.x,(p:{x:number;z:number})=>p.z+34,(p:{x:number;z:number})=>34-p.z])points=clipPolygon(points,distance);return points;})).filter(r=>r.length>2)})).filter(c=>c.rings.length);},[data,scene.journeyLayout]);
 useEffect(()=>{const abort=new AbortController();fetch('/maps/natural-earth.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setData).catch(()=>{if(!abort.signal.aborted)setError('Geographic outline unavailable. Episode coordinates remain intact.');});return()=>abort.abort();},[]);
 useEffect(()=>{const el=canvas.current;if(!el)return;const draw=()=>{const {width:w,height:h}=el.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1);el.width=w*ratio;el.height=h*ratio;const ctx=el.getContext('2d')!;ctx.setTransform(ratio,0,0,ratio,0,0);const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,'#081722');bg.addColorStop(1,'#171528');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);const project=(p:{x:number;z:number;y?:number})=>atlasProject(p,view,w,h);function line(a:{x:number;z:number;y?:number},b:{x:number;z:number;y?:number},color:string,dash=false){const p=project(a),q=project(b);ctx.beginPath();ctx.setLineDash(dash?[3,6]:[]);ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.strokeStyle=color;ctx.stroke();ctx.setLineDash([]);}
 for(const country of map){for(const ring of country.rings){ctx.beginPath();ring.map(project).forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fillStyle='#779f9811';ctx.fill();ctx.strokeStyle='#9dbcbf66';ctx.lineWidth=.65;ctx.stroke();}if(Math.abs(country.label.x)<29&&Math.abs(country.label.z)<29){const p=project(country.label);ctx.font='9px monospace';ctx.fillStyle='#8caeb2';ctx.textAlign='center';ctx.fillText(country.name.toUpperCase(),p.x,p.y);}}
 line({x:-30,z:30},{x:30,z:30},'#a1c9c744');line({x:-30,z:30},{x:-30,z:-30},'#a1c9c744');const north=project({x:-30,z:-31});ctx.fillStyle='#bedcd7';ctx.font='10px monospace';ctx.fillText('N ↑',north.x,north.y);
 const placed=spaces.map((s,i)=>({...((memory?s.memory:s.world)),y:memory?chronologicalHeight(s.start,spaces[0].start,spaces.at(-1)!.end):.15,index:i}));
 for(let i=1;i<placed.length;i++)line(placed[i-1],placed[i],'#dabb7d80',true);
 hits.current=[];
 for(const p of [...placed].sort((a,b)=>project(a).y-project(b).y)){const s=spaces[p.index],focus=p.index===selected,base=memory?s.memory:s.world;
 if(memory){line({...base,y:0},p,'#bcb9dd55',true);line(s.world,s.memory,'#f3c278',false);const g=project(s.world);ctx.strokeStyle='#bddddc88';ctx.setLineDash([2,3]);ctx.strokeRect(g.x-5,g.y-3,10,6);ctx.setLineDash([]);}
 const qty=acceptedDensity(s,decisions),count=Math.min(24,Math.ceil(qty/25));for(let j=0;j<count;j++){const x=p.x-.65+(j%8)*.18;line({x,z:p.z,y:p.y},{x,z:p.z,y:p.y+.3+(Math.floor(j/8)+1)*.35},'#e8c589aa');}
 if(focus){const labels=s.selections.filter(a=>decisions[a.cueId]==='accepted').slice(0,2).map(a=>`${scene.cues.find(c=>c.id===a.cueId)?.title??''} · ${a.count} matches`);labels.forEach((label,j)=>{const t=project(p);ctx.font='italic 11px Georgia';ctx.fillStyle='#e8cca0';ctx.textAlign='left';ctx.fillText(label.slice(0,60),t.x+14,t.y-34-j*16);});}
 const layers=Math.min(6,s.members.length);for(let j=layers-1;j>=0;j--){const points=[{x:p.x-.8,z:p.z-.5,y:p.y+j*.13},{x:p.x+.8,z:p.z-.5,y:p.y+j*.13},{x:p.x+.8,z:p.z+.5,y:p.y+j*.13},{x:p.x-.8,z:p.z+.5,y:p.y+j*.13}].map(project);ctx.beginPath();points.forEach((q,i)=>i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y));ctx.closePath();ctx.fillStyle=s.author?'#b99ddb33':'#91d0c633';ctx.fill();ctx.strokeStyle=focus?'#f3e7c6':'#a9ced499';ctx.lineWidth=focus?1.7:.8;ctx.stroke();}
 const screen=project(p);hits.current.push({...screen,index:p.index});if(focus||view.zoom>1.7){ctx.font=focus?'14px Georgia':'10px Georgia';ctx.fillStyle='#eee7d5';ctx.textAlign='left';ctx.fillText(`${String(p.index+1).padStart(2,'0')} / ${s.label}`,screen.x+14,screen.y-10);}
 }
 if(memory){const a={x:-27,z:26,y:0},b={...a,y:14};line(a,b,'#c5bde7aa');const t=project(b);ctx.fillStyle='#c5bde7';ctx.font='10px monospace';ctx.textAlign='left';ctx.fillText('TIME ↑ · elapsed days',t.x+8,t.y);}
 ctx.textAlign='left';};draw();const observer=new ResizeObserver(draw);observer.observe(el);return()=>observer.disconnect();},[spaces,map,view,memory,selected,decisions,scene.cues]);
 function move(dx:number,dz:number){onChange(moveEpisodeSpace(scene,current,dx,dz,'WORLD'));}
 return <section className={`${css.atlas} ${full?css.full:''}`}><header><div><p>SPATIAL REHEARSAL / {memory?'MEMORY':'WORLD'}</p><h2>{memory?<>A geography<br/><em>held in time.</em></>:<>The shape<br/><em>of being somewhere.</em></>}</h2></div><nav aria-label="Spatial regime">{(['WORLD','TIME','MEMORY'] as Regime[]).map(r=><button key={r} aria-pressed={r===(memory?'MEMORY':'WORLD')} onClick={()=>{setView(r==='MEMORY'?MEMORY_ATLAS_VIEW:DEFAULT_ATLAS_VIEW);onRegime(r);}}>{r}</button>)}</nav></header>
 <canvas ref={canvas} aria-label="Geographic atlas. Drag to orbit, scroll to zoom. Select an episode. Use controls below for keyboard navigation." tabIndex={0} onKeyDown={e=>{if(e.key==='Escape'){setFull(false);setMoving(false);}if(e.key==='ArrowLeft')setView(v=>({...v,yaw:v.yaw-.1}));if(e.key==='ArrowRight')setView(v=>({...v,yaw:v.yaw+.1}));if(e.key==='+'||e.key==='=')setView(v=>({...v,zoom:Math.min(5,v.zoom*1.1)}));if(e.key==='-')setView(v=>({...v,zoom:Math.max(.35,v.zoom/1.1)}));}} onWheel={e=>{setView(v=>({...v,zoom:Math.max(.35,Math.min(5,v.zoom*Math.exp(-Math.sign(e.deltaY)*.09)))}));}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);gesture.current={x:e.clientX,y:e.clientY,view};}} onPointerMove={e=>{const g=gesture.current;if(g&&!moving)setView({...g.view,yaw:g.view.yaw+(e.clientX-g.x)*.005,tilt:Math.max(.3,Math.min(1.4,g.view.tilt+(e.clientY-g.y)*.003))});}} onPointerCancel={()=>gesture.current=null} onPointerUp={e=>{const g=gesture.current;gesture.current=null;if(!g)return;const dx=e.clientX-g.x,dy=e.clientY-g.y,rect=e.currentTarget.getBoundingClientRect();if(memory&&moving){const offset=atlasDrag(dx,dy,view,rect.width,rect.height);move(offset.x,offset.z);}else if(Math.hypot(dx,dy)<5){const hit=[...hits.current].sort((a,b)=>Math.hypot(a.x-e.clientX+rect.left,a.y-e.clientY+rect.top)-Math.hypot(b.x-e.clientX+rect.left,b.y-e.clientY+rect.top))[0];if(hit&&Math.hypot(hit.x-e.clientX+rect.left,hit.y-e.clientY+rect.top)<35)setSelected(hit.index);}}}/>
 <div className={css.caption}><span>{String(selected+1).padStart(2,'0')} / {spaces.length} EPISODES</span><h3>{current.label}</h3><p>{current.start.slice(0,10)} → {current.end.slice(0,10)} · {current.count} observed plays · {current.members.length} source windows</p></div>
 <div className={css.controls}><button disabled={selected===0} onClick={()=>setSelected(i=>i-1)}>← Earlier</button><button disabled={selected===spaces.length-1} onClick={()=>setSelected(i=>i+1)}>Later →</button><button onClick={()=>setView(memory?MEMORY_ATLAS_VIEW:DEFAULT_ATLAS_VIEW)}>{memory?'Time-axis view':'Reset view'}</button><button onClick={()=>setView(v=>({...v,zoom:Math.min(5,v.zoom*1.2)}))}>Zoom in</button><button onClick={()=>setView(v=>({...v,zoom:Math.max(.35,v.zoom/1.2)}))}>Zoom out</button><XRMemorySound key={`${memory}:${current.id}`} scene={scene} episodeId={current.id} label={current.label} pan={Math.max(-1,Math.min(1,((memory?current.memory:current.world).x*Math.cos(view.yaw)-(memory?current.memory:current.world).z*Math.sin(view.yaw))/20))} activated={activated} onChange={onChange}/><button onClick={()=>setInspect(v=>!v)}>{inspect?"Close evidence":"Evidence & composition"}</button><button onClick={()=>setFull(v=>!v)}>{full?'Leave immersive':'Enter immersive'}</button>{memory&&<><button aria-pressed={moving} onClick={()=>setMoving(v=>!v)}>{moving?'Finish moving':'Drag selected episode'}</button><button onClick={()=>move(-1,0)}>West</button><button onClick={()=>move(1,0)}>East</button><button onClick={()=>move(0,-1)}>North</button><button onClick={()=>move(0,1)}>South</button></>}</div>
 {inspect&&<aside className={css.evidence}><button onClick={()=>setInspect(false)}>Close evidence</button><h3>{current.label}</h3><p>{current.members.length} source windows · {current.count} observed plays. Source evidence and composition stay separate.</p><p>WORLD {current.world.x.toFixed(2)}, {current.world.z.toFixed(2)} → MEMORY {current.memory.x.toFixed(2)}, {current.memory.z.toFixed(2)}.</p><button onClick={()=>{setFull(false);setInspect(false);onInspect(current.members[0]);}}>Inspect source windows</button><button onClick={()=>onRegime('TIME')}>Walk / listen in TIME</button><h4>Author fragment placement</h4>{scene.cues.filter(c=>c.source==='author'&&decisions[c.id]==='accepted').map(c=><div key={c.id}><p>{c.title}</p>{[true,false].map(place=><button key={String(place)} onClick={()=>onChange({...scene,experience:{...(scene.experience??{regime:memory?'MEMORY':'WORLD',memoryBase:'WORLD',fragmentDecisions:[]}),fragmentDecisions:[...(scene.experience?.fragmentDecisions??[]),{cueId:c.id,episodeId:place?current.id:null,at:new Date().toISOString(),author:'Author',interpretation:'Composition only; no factual association inferred'}]}})}>{place?'Place here':'Leave unplaced'}</button>)}</div>)}<p>Save review to Vault preserves moves and placements. No event meaning is inferred.</p></aside>}
 <p className={css.legend}>{memory?'Ground: geographic ghost. Height: elapsed chronology. Solid amber: saved Author displacement; dotted vertical: time display. Save review to retain moves.':'Geographic positions are locked. Drag to orbit · scroll to zoom. Dashed connections show episode order, not travelled routes.'} Gold filaments: accepted listening matches, one per 25, capped at 24. Plates: source-window count, capped at six.</p><small><a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth</a> · generalised country outlines · existing uniform geographic projection. No terrain height or emotional meaning inferred. {error}</small></section>;
}
